# Generated by Django 5.1.1 on 2024-09-25 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saintApp', '0003_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
