# Generated by Django 5.1.1 on 2024-09-26 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saintApp', '0008_alter_user_date_joined_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
