# Generated by Django 5.1.1 on 2024-09-26 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saintApp', '0009_alter_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
