# Generated by Django 5.1.1 on 2024-10-28 08:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saintApp', '0015_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
